double** runMcCaskill(char sequence[MAXSIZE]);
void solveZ(int i, int j, double x, char sequence[MAXSIZE], int *basePairs, int **basePairCounts,  double **Z,  double **ZB);
void solveZB(int i, int j, double x, char sequence[MAXSIZE], int *basePairs, int **basePairCounts, double **ZB, double **ZM);
void solveZM(int i, int j, double x, char sequence[MAXSIZE], int *basePairs, int **basePairCounts, double **ZB, double **ZM);
void solveLinearSystem(double **rootsOfUnity, double **Z);
int jPairedIn(int i, int j, int *basePairs);
int jPairedTo(int i, int j, int *basePairs);
int* getBasePairList(char *structure);
int numberOfBasePairs(int i, int j, int *basePairs);
int** fillBasePairCounts(int *basePairs, int n);
void printMatrix(double **matrix, char *title, int iStart, int iStop, int jStart, int jStop);
